---
#### Startup
# -------
- repo: Shougo/dein.vim
- repo: rafi/awesome-vim-colorschemes
- repo: rafi/vim-badge
- repo: numkil/ag.nvim
- repo: thinca/vim-localrc
- repo: christoomey/vim-tmux-navigator
- repo: junegunn/vim-peekaboo
- repo: tpope/vim-sleuth
- repo: itchyny/vim-gitbranch
- repo: itchyny/vim-parenmatch
- repo: itchyny/vim-cursorword
  hook_add: |
    autocmd MyAutoCmd FileType denite,qf,nerdtree let b:cursorword=0
    autocmd MyAutoCmd InsertEnter * let b:cursorword=0
    autocmd MyAutoCmd InsertLeave * let b:cursorword=1

#### Misc
# ---------
#### Languages
- { repo: chrisbra/NrrwRgn }

#### Language: CSS
- { repo: hail2u/vim-css3-syntax, on_ft: css }
- { repo: ap/vim-css-color, on_ft: [ css, scss, sass ] }
- { repo: cakebaker/scss-syntax.vim, on_ft: [ scss, sass ]}
- { repo: groenewege/vim-less, on_ft: less }
- { repo: othree/csscomplete.vim, on_ft: css }
- { repo: guns/xterm-color-table.vim, on_cmd: XtermColorTable }

#### Language: Ansible
- { repo: pearofducks/ansible-vim, on_ft: ansible }

#### Language: HTML
- repo: othree/html5.vim
  on_ft: html
  hook_add: |
    let g:html5_event_handler_attributes_complete = 0
    let g:html5_rdfa_attributes_complete = 0
    let g:html5_microdata_attributes_complete = 0
    let g:html5_aria_attributes_complete = 0

#### Language: MARKDOWN
- repo: plasticboy/vim-markdown
  on_ft: markdown
  hook_add: |
    let g:vim_markdown_override_foldtext = 0
    let g:vim_markdown_initial_foldlevel = 999
    let g:vim_markdown_new_list_item_indent = 2
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_conceal = 0
    let g:vim_markdown_fenced_languages = [
      \ 'c++=cpp',
      \ 'viml=vim',
      \ 'bash=sh',
      \ 'ini=dosini'
      \ ]

- repo: rhysd/vim-gfm-syntax
  depends: vim-markdown
  on_ft: markdown
  hook_source: |
    let g:gfm_syntax_enable_always = 0
    let g:gfm_syntax_highlight_emoji = 0
    let g:gfm_syntax_enable_filetypes = ['markdown']

#### Language: JAVASCRIPT
- repo: pangloss/vim-javascript
  on_ft: [ javascript, jsx, javascript.jsx ]
  hook_source: |
    let g:javascript_plugin_jsdoc = 1
    let g:javascript_plugin_flow = 1
    highlight! link jsFutureKeys PreProc

- { repo: othree/jspc.vim, on_ft: [ javascript, jsx, javascript.jsx ] }
- { repo: MaxMEllon/vim-jsx-pretty, on_ft: [ javascript, jsx, javascript.jsx ]}
- { repo: heavenshell/vim-jsdoc, on_ft: [ javascript, jsx, javascript.jsx ] }
- { repo: elzr/vim-json, on_ft: json }
- { repo: Galooshi/vim-import-js, on_ft: javascript }

#### Language: GO
- repo: fatih/vim-go
  on_ft: go
  hook_source: |
    let g:go_def_mapping_enabled = 0
    let g:go_loaded_gosnippets = 1
    let g:go_snippet_engine = 'neosnippet'
    let g:go_highlight_extra_types = 1
    let g:go_highlight_operators = 1

#### Language: PYTHON
- { repo: vim-python/python-syntax, on_ft: python }
- { repo: Vimjas/vim-python-pep8-indent, on_ft: python }
- { repo: vim-scripts/python_match.vim, on_ft: python }
- { repo: tmhedberg/SimpylFold, on_ft: python }
- { repo: bps/vim-textobj-python, on_ft: python }
- { repo: phillipberndt/python-imports.vim, on_ft: python }
- { repo: vim-scripts/tagport, on_ft: python }
- { repo: heavenshell/vim-pydocstring, on_ft: python }
- { repo: stsewd/isort.nvim, on_ft: python }
- { repo: raimon49/requirements.txt.vim, on_ft: requirements }

#### Language: LUA
- { repo: tbastos/vim-lua, on_ft: lua }

#### Language: RUBY
- { repo: osyo-manga/vim-monster, on_ft: ruby }
- { repo: vim-ruby/vim-ruby, on_ft: ruby }
- { repo: tpope/vim-rails, on_ft: ruby }
- { repo: ecomba/vim-ruby-refactoring, on_ft: ruby }


#### Language: SWIFT
- { repo: toyamarinyon/vim-swift, on_ft: swift }

#### Language: VIM SCRIPT
- { repo: vim-jp/syntax-vim-ex, on_ft: vim }

#### Language: CSV
- { repo: chrisbra/csv.vim, on_ft: csv }

#### Language: PGSQL
- { repo: exu/pgsql.vim, on_ft: pgsql }

#### Language: NGINX
- { repo: othree/nginx-contrib-vim, on_ft: nginx }

#### Language: LOGS
- { repo: andreshazard/vim-logreview, on_ft: logreview }

#### Language: DOCKER
- { repo: ekalinin/Dockerfile.vim, on_ft: [ Dockerfile, docker-compose ]}

#### Language: TMUX
- { repo: tmux-plugins/vim-tmux, on_ft: tmux }

#### GIT
- { repo: tpope/vim-git, on_ft: [ gitcommit, gitrebase, gitconfig ]}

#### Commands
- repo: scrooloose/nerdtree
  depends: nerdtree-git-plugin
  on_map: { n: <Plug> }
  hook_post_source: source $VIMPATH/config/plugins/nerdtree.vim

- { repo: terryma/vim-multiple-cursors }
- { repo: godlygeek/tabular, on_cmd: Tabularize }
- { repo: Xuyuanp/nerdtree-git-plugin, on_source: nerdtree }
- { repo: ryanoasis/vim-devicons, on_source: nerdtree }
- { repo: tpope/vim-commentary, on_map: <Plug>Commentary }
- { repo: kana/vim-niceblock, on_map: { x: <Plug> }}
- { repo: mbbill/undotree, on_cmd: UndotreeToggle }
- { repo: metakirby5/codi.vim, on_cmd: Codi, if: empty($VIM_MINIMAL) }
- { repo: Shougo/vimproc.vim, build: make, on_func: vimproc# }
- { repo: reedes/vim-wordy, on_cmd: [ Wordy, NextWordy, PrevWordy ]}
- { repo: brooth/far.vim, on_cmd: [ Far, Farp, F ] }
- { repo: jreybert/vimagit, on_cmd: Magit }

- repo: easymotion/vim-easymotion
  on_map: { n: <Plug> }
  hook_source: |
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to → '
    let g:EasyMotion_keys = 'fjdksweoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1

- repo: chemzqm/vim-easygit
  on_cmd: [ Gcd, Glcd, Gcommit, Gblame, Gstatus, Gdiff, Gbrowse, Gstatus, Gpush ]
  hook_source: let g:easygit_enable_command = 1

- repo: majutsushi/tagbar
  if: empty($VIM_MINIMAL)
  on_cmd: TagbarToggle
  hook_source: |
    let g:tagbar_width = 40
    if executable('jsctags')
      let g:tagbar_type_javascript = { 'ctagsbin': 'jsctags' }
    endif

- repo: beloglazov/vim-online-thesaurus
  if: empty($VIM_MINIMAL)
  on_cmd: [ OnlineThesaurusCurrentWord, Thesaurus ]
  hook_source: let g:online_thesaurus_map_keys = 0

# ==========================================
# Interface
# ---------
- { repo: haya14busa/vim-asterisk, on_map: { nv: <Plug> }}
- { repo: rhysd/accelerated-jk, on_map: { n: <Plug> }}

- repo: airblade/vim-gitgutter
  on_path: .*
  hook_source: |
    let g:gitgutter_map_keys = 0
    let g:gitgutter_sh = $SHELL

- repo: nathanaelkane/vim-indent-guides
  on_cmd: [ IndentGuidesEnable, IndentGuidesDisable, IndentGuidesToggle ]
  hook_post_source: |
    call indent_guides#init_script_vars()
    call indent_guides#highlight_colors()
  hook_add: |
    let g:indent_guides_color_change_percent = 3
    let g:indent_guides_autocmds_enabled = 0
    let g:indent_guides_default_mapping = 0
    let g:indent_guides_guide_size = 1
    let g:indent_guides_indent_levels = 15
    let g:custom_exclude = [ 'help', 'denite', 'codi' ]
    autocmd MyAutoCmd BufEnter *
      \ if ! empty(&l:filetype) && index(g:custom_exclude, &l:filetype) == -1
      \|   if g:indent_guides_autocmds_enabled == 0 && &l:expandtab
      \|     IndentGuidesEnable
      \|   elseif g:indent_guides_autocmds_enabled == 1 && ! &l:expandtab
      \|     IndentGuidesDisable
      \|   endif
      \| endif

- repo: MattesGroeger/vim-bookmarks
  on_path: .*
  hook_source: |
    let g:bookmark_auto_save_file = $VARPATH.'/bookmarks'
    let g:bookmark_no_default_key_mappings = 1
    let g:bookmark_disable_ctrlp = 1

- repo: rhysd/committia.vim
  on_path: COMMIT_EDITMSG
  hook_source: let g:committia_min_window_width = 70

- repo: benekastah/neomake
  if: has('nvim') && empty($VIM_MINIMAL)
  on_cmd: Neomake
  hook_source: source $VIMPATH/config/plugins/neomake.vim
  hook_add: |
    let g:lint_filetypes = [
      \  'ansible', 'python', 'php', 'ruby', 'vim', 'go', 'sh',
      \  'javascript', 'jsx', 'javascript.jsx', 'json', 'css',
      \  'markdown', 'html', 'yaml'
      \ ]
    autocmd MyAutoCmd BufWritePost *
      \ if index(g:lint_filetypes, &filetype) > -1 && empty(&buftype)
      \|   Neomake
      \| elseif &filetype =~ 'html'
      \|   Neomake tidy
      \| endif

- repo: junegunn/goyo.vim
  if: empty($VIM_MINIMAL)
  depends: limelight.vim
  on_cmd: Goyo
  hook_source: source $VIMPATH/config/plugins/goyo.vim

- repo: junegunn/limelight.vim
  if: empty($VIM_MINIMAL)
  on_cmd: Limelight

- repo: itchyny/calendar.vim
  if: empty($VIM_MINIMAL)
  on_cmd: Calendar
  hook_source: |
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1

- repo: vimwiki/vimwiki
  if: empty($VIM_MINIMAL)
  on_map: { n: <Plug> }
  on_cmd: Vimwiki
  hook_add: |
    let g:vimwiki_use_calendar = 1
    let g:vimwiki_hl_headers = 1
    let g:vimwiki_hl_cb_checked = 1
    let g:vimwiki_autowriteall = 0
  hook_source: |
    let g:vimwiki_list = [
    \   { 'diary_header': 'Diary',
    \     'diary_link_fmt': '%Y-%m/%d',
    \     'auto_toc': 1,
    \     'path': '~/docs/wiki/',
    \     'syntax': 'markdown',
    \     'ext': '.md' },
    \   { 'path': '~/docs/blog/',
    \     'syntax': 'markdown',
    \     'ext': '.md' }
    \ ]

# ==========================================
# Completion
# ----------
- repo: Shougo/deoplete.nvim
  depends: context_filetype.vim
  if: has('nvim') && empty($VIM_MINIMAL)
  on_i: 1
  hook_add: let g:deoplete#enable_at_startup = 1
  hook_source: source $VIMPATH/config/plugins/deoplete.vim

- repo: Shougo/neocomplete
  depends: context_filetype.vim
  if: ! has('nvim') && has('lua') && empty($VIM_MINIMAL)
  on_event: InsertEnter
  hook_add: |
    let g:neocomplete#data_directory = $VARPATH.'/complete'
    let g:neocomplete#enable_at_startup = 1
  hook_source: source $VIMPATH/config/plugins/neocomplete.vim

- repo: Shougo/neosnippet.vim
  depends: [ neosnippet-snippets, context_filetype.vim ]
  if: empty($VIM_MINIMAL)
  on_event: InsertCharPre
  on_ft: snippet
  hook_add: let g:neosnippet#data_directory = $VARPATH.'/snippets'
  hook_source: |
    let g:neosnippet#enable_snipmate_compatibility = 1
    let g:neosnippet#enable_completed_snippet = 1
    let g:neosnippet#expand_word_boundary = 1
    autocmd MyAutoCmd InsertLeave * NeoSnippetClearMarkers

- repo: ludovicchabant/vim-gutentags
  if: executable('ctags') && empty($VIM_MINIMAL)
  on_path: .*
  hook_add: |
    let g:gutentags_cache_dir = $VARPATH.'/tags'
    let g:gutentags_generate_on_write = 1
    let g:gutentags_generate_on_missing = 0
    let g:gutentags_generate_on_new = 0

- repo: mattn/emmet-vim
  if: empty($VIM_MINIMAL)
  on_i: 1
  on_ft: [ html, css, jsx, javascript, javascript.jsx, eruby ]
  hook_source: |
    let g:use_emmet_complete_tag = 0
    let g:user_emmet_install_global = 0
    let g:user_emmet_install_command = 0
    let g:user_emmet_mode = 'i'

- repo: Shougo/echodoc.vim
  if: empty($VIM_MINIMAL)
  on_event: CompleteDone
  hook_post_source: call echodoc#enable()

- repo: Raimondi/delimitMate
  on_i: 1
  hook_source: |
    let g:delimitMate_expand_cr = 1
    let g:delimitMate_excluded_ft = 'html'

- { repo: Shougo/neosnippet-snippets, if: empty($VIM_MINIMAL) }
- { repo: Shougo/context_filetype.vim, lazy: 1, if: empty($VIM_MINIMAL) }
- { repo: Shougo/neco-vim, on_ft: vim, if: empty($VIM_MINIMAL) }
- { repo: Shougo/neco-syntax, on_source: [ neocomplete.vim, deoplete.nvim ]}

- repo: davidhalter/jedi-vim
  if: empty($VIM_MINIMAL)
  on_ft: python
  hook_add: |
    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#smart_auto_mappings = 0
    let g:jedi#show_call_signatures = 1
  hook_source: |
    let g:jedi#use_tag_stack = 0
    let g:jedi#popup_select_first = 0
    let g:jedi#popup_on_dot = 0
    let g:jedi#max_doc_height = 100
    let g:jedi#quickfix_window_height = 10
    let g:jedi#use_splits_not_buffers = 'right'

# Only NeoVim ------------------------------
- repo: zchee/deoplete-go
  if: has('nvim') && empty($VIM_MINIMAL)
  on_ft: go
  on_i: 1

- repo: junegunn/fzf
  if: has('nvim') && empty($VIM_MINIMAL)
  build: ./install --all

- repo: zchee/deoplete-jedi
  if: has('nvim') && empty($VIM_MINIMAL)
  on_ft: python
  on_i: 1
  hook_source: autocmd MyAutoCmd FileType python setlocal omnifunc=

- repo: carlitux/deoplete-ternjs
  build: npm install -g tern
  if: executable('npm') && has('nvim') && empty($VIM_MINIMAL)
  on_i: 1
  on_ft: [ javascript, jsx, javascript.jsx ]
  hook_source: |
    let g:tern_request_timeout = 1
    let g:tern_show_signature_in_pum = 0

- repo: wellle/tmux-complete.vim
  if: has('nvim') && empty($VIM_MINIMAL)
  on_i: 1
  hook_add: let g:tmuxcomplete#trigger = ''

- repo: ternjs/tern_for_vim
  build: npm install
  if: executable('npm') && empty($VIM_MINIMAL)
  on_i: 1
  on_ft: [ javascript, jsx, javascript.jsx ]
  hook_add: |
    let g:tern#command = ['tern']
    let g:tern#arguments = ['--persistent']
    let g:tern_request_timeout = 1
    let g:tern_show_signature_in_pum = 0
  hook_post_source: |
    autocmd MyAutoCmd FileType javascript setlocal omnifunc=tern#Complete

# ==========================================
# Denite
# ------
- repo: Shougo/denite.nvim
  on_cmd: Denite
  hook_source: source $VIMPATH/config/plugins/denite.vim
  hook_post_source: source $VIMPATH/config/menus.vim

- { repo: chemzqm/unite-location, on_source: denite.nvim }
- { repo: chemzqm/denite-git, on_source: denite.nvim }
- { repo: rafi/vim-denite-z, on_source: denite.nvim }
- { repo: rafi/vim-denite-session, on_source: denite.nvim }

- repo: rafi/vim-denite-mpc
  if: executable('mpc') && empty($VIM_MINIMAL)
  on_source: denite.nvim
  hook_source: call denite#custom#var('mpc', 'default_view', 'date')

# ==========================================
# Operators
# ---------
- { repo: kana/vim-operator-user, lazy: 1 }

- repo: kana/vim-operator-replace
  depends: vim-operator-user
  on_map: { vnx: <Plug> }

- repo: tpope/vim-surround

- repo: haya14busa/vim-operator-flashy
  depends: vim-operator-user
  on_map: { nx: <Plug> }

# ==========================================
# Text objects
# ------------
- { repo: kana/vim-textobj-user, lazy: 1 }

- { repo: vim-scripts/vim-indent-object }
- { repo: lucapette/vim-textobj-underscore, depends: vim-textobj-user }
- { repo: nelstrom/vim-textobj-rubyblock, depends: vim-textobj-user, on_ft: ruby }
- { repo: kana/vim-textobj-entire, depends: vim-textobj-user }
- { repo: bkad/CamelCaseMotion, on_map: { nox: <Plug>CamelCaseMotion }}
- { repo: terryma/vim-expand-region, on_map: { x: <Plug> }}
- { repo: AndrewRadev/sideways.vim, on_map: { ox: <Plug>Sideways }}
- { repo: AndrewRadev/splitjoin.vim, on_map: { n: <Plug>Splitjoin }}
- { repo: AndrewRadev/linediff.vim, on_cmd: Linediff }

- repo: AndrewRadev/dsf.vim
  on_map: { n: <Plug>Dsf }
  hook_add: let g:dsf_no_mappings = 1

- repo: osyo-manga/vim-textobj-multiblock
  depends: vim-textobj-user
  on_map: { ox: <Plug> }
  hook_add: let g:textobj_multiblock_no_default_key_mappings = 1

- repo: kana/vim-textobj-function
  depends: vim-textobj-user
  on_map: { ox: <Plug> }
  hook_add: let g:textobj_function_no_default_key_mappings = 1

#  vim: set foldmethod=indent ts=2 sw=2 tw=80 et :
